### ISSUE TITLE
Exception thrown from completion handler not propagated through io_service::run()

### ISSUE THREAD

**Issue by nobleread** [ceph/spawn#1]
I've noticed that exceptions thrown from within spawn::spawn'ed coroutines are not propagated through `io_service::run()` (older `io_context::run()`), but rather program terminates with core dump. 

Below is a minimal example to reproduce this error. Of course, when using `boost::asio::spawn` instead of `spawn::spawn`, everything [works as it should](https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/io_service.html#boost_asio.reference.io_service.effect_of_exceptions_thrown_from_handlers).

```
#include <iostream>

#include <boost/asio/io_service.hpp>
#include <boost/asio/spawn.hpp>

#include <spawn/spawn.hpp>

int main() {
    boost::asio::io_service io_service;
    //boost::asio::spawn(io_service, [&](boost::asio::yield_context yield) { throw 5; });
    spawn::spawn(io_service, [&](spawn::yield_context yield) { throw 5; });
    for (;;) {
        try {
            io_service.run();
            return 0;
        } catch (...) {
            std::cout << "catched" << std::endl;
        }
    }
}
```
For invocation with spawn::spawn, program outputs:
```
terminate called after throwing an instance of 'int'
Aborted (core dumped)
```
For boost::asio::spawn:
```
catched
```

**Comment by cbodley** [comment]
resolved in https://github.com/cbodley/spawn/issues/1. the relevant fixes were applied here too
